openapi: 3.0.0
info:
  title: Housing Matching Service
  version: 3.0.0
servers:
  - url: 'https://www.hslynk.com/house-matching-api/'
paths:
  /v3/matches:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                    links:
                    - rel: first
                      href: https://www.hslynk.com/house-matching-api/v3/matches?page=0&size=20
                    - rel: self
                      href: https://www.hslynk.com/house-matching-api/v3/matches
                    - rel: next
                      href: https://www.hslynk.com/house-matching-api/v3/matches?page=1&size=20
                    - rel: last
                      href: https://www.hslynk.com/house-matching-api/v3/matches?page=3&size=20
                    content:
                    - reservationId: a8d6e4b6-cac6-4e01-9d81-1abf1b361141
                      eligibleClients:
                        clientId: 37c1ddf1-1d09-437e-8a01-af3801049c43
                        surveyScore: 5
                        programType: '2'
                        matched: true
                        surveyDate: 2016-12-20 00:00
                        spdatLabel: SINGLE_ADULT
                        dateCreated: 2016-12-20 07:51
                        dateUpdated: 2017-02-18 18:56
                        ignoreMatchProcess: false
                        remarks: Ignore match flag auto set by system to false
                        bonusScore: 0
                        totalScore: 5
                      housingUnitId: 3bc26f92-11c9-4fd8-a33a-bba98859e14d
                      matchDate: '2016-12-20'
                      matchStatus: 0
                      manualMatch: false
                      dateCreated: 2016-12-20 08:33
                      dateUpdated: 2016-12-20 08:33
                      links:
                      - rel: history
                        href: "/matches/client/37c1ddf1-1d09-437e-8a01-af3801049c43/status"
                      - rel: client
                        href: "/hmis-clientapi/rest/v2015/clients/37c1ddf1-1d09-437e-8a01-af3801049c43"
                    - reservationId: 8379d701-59f7-4832-96d1-5dbf0b8761b0
                      eligibleClients:
                        clientId: 049f398d-e048-400d-adb6-d74ced86ee63
                        surveyScore: 5
                        programType: '2'
                        matched: true
                        surveyDate: 2016-12-20 00:00
                        spdatLabel: SINGLE_ADULT
                        dateCreated: 2016-12-20 08:13
                        dateUpdated: 2017-02-18 18:55
                        ignoreMatchProcess: false
                        remarks: Ignore match flag auto set by system to false
                        bonusScore: 0
                        totalScore: 5
                      housingUnitId: 196b83b6-d546-40a7-b72a-3bc2770064b0
                      matchDate: '2016-12-20'
                      matchStatus: 0
                      manualMatch: false
                      dateCreated: 2016-12-20 08:33
                      dateUpdated: 2016-12-20 08:33
                      links:
                      - rel: history
                        href: "/matches/client/049f398d-e048-400d-adb6-d74ced86ee63/status"
                      - rel: client
                        href: "/hmis-clientapi/rest/v2015/clients/049f398d-e048-400d-adb6-d74ced86ee63"
                    - reservationId: f450c258-326b-4f4a-9c3f-0a6d6ae6fa58
                      eligibleClients:
                        clientId: e23b264e-b69f-446e-84e7-58e3fe00e0f1
                        surveyScore: 5
                        programType: '2'
                        matched: true
                        surveyDate: 2016-12-20 00:00
                        spdatLabel: SINGLE_ADULT
                        dateCreated: 2016-12-20 08:33
                        dateUpdated: 2017-02-18 18:54
                        ignoreMatchProcess: false
                        remarks: Ignore match flag auto set by system to false
                        bonusScore: 0
                        totalScore: 5
                      housingUnitId: 68e75874-f62c-4436-b12b-a540d7977869
                      matchDate: '2016-12-20'
                      matchStatus: 0
                      manualMatch: false
                      dateCreated: 2016-12-20 08:33
                      dateUpdated: 2016-12-20 08:33
                      links:
                      - rel: history
                        href: "/matches/client/e23b264e-b69f-446e-84e7-58e3fe00e0f1/status"
                      - rel: client
                        href: "/hmis-clientapi/rest/v2015/clients/e23b264e-b69f-446e-84e7-58e3fe00e0f1"
                    page:
                      size: 20
                      totalElements: 73
                      totalPages: 4
                      number: 0
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error: Token Not Valid
      description: Get the list of the proposed matches.
      operationId: GET_matches
  '/v3/matches/client/{dedupClientId}':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  reservation_id: '12345'
                  client_id: '456788'
                  housing_unit_id: 09876
                  match_date: '2016-10-10'
                  dateCreated: '10-25-2016 15:24'
                  dateUpdated: '10-25-2016 15:24'
                  userId: 74fe590d-9389-4936-abef-1c18fbf14750
                  matchedStatus: 'true'
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error: Token Not Valid
      description: Get the proposed matche for a client_id.
      operationId: GET_matches-client-dedupClientId
    delete:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  deleted: ok
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error: Token Not Valid
      description: |
        Clears off the proposed match for a particular client.
      operationId: DELETE_matches-client-dedupClientId
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  matched: ok
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error: Token Not Valid
      description: |
        Used for updating/accepting the match for a client id.
      operationId: PUT_matches-client-dedupClientId
      requestBody:
        content:
          application/json:
            example:
              reservationAdults: '0'
              reservationChildren: '2'
            schema:
              type: string
        required: true
    parameters:
      - name: dedupClientId
        in: path
        required: true
        schema:
          type: string
        description: id of the client.
  /v3/eligibleclients:
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example: |
                  {
                     "links":[
                        {
                           "rel":"first",
                           "href":"https://www.hslynk.com/house-matching-api/v3/eligibleclients?page=0&size=1"
                        },
                        {
                           "rel":"self",
                           "href":"https://www.hslynk.com/house-matching-api/v3/eligibleclients?size=1"
                        },
                        {
                           "rel":"next",
                           "href":"https://www.hslynk.com/house-matching-api/v3/eligibleclients?page=1&size=1"
                        },
                        {
                           "rel":"last",
                           "href":"https://www.hslynk.com/house-matching-api/v3/eligibleclients?page=2&size=1"
                        },
                        {
                           "rel":"scoreprocessingstatus",
                           "href":"https://www.hslynk.com/house-matching-api/scores/status"
                        },
                        {
                           "rel":"scoreprocessinghistory",
                           "href":"https://www.hslynk.com/house-matching-api/scores/history"
                        }
                     ],
                     "content":[
                        {
                           "clientId":"91dbc8c3-6df6-4702-9733-c84dd67bf1ed",
                           "surveyScore":10,
                           "matched":false,
                           "surveyDate":"09-29-2016 11:05",
                           "dateCreated":"10-25-2016 15:24",
                           "dateUpdated":"10-25-2016 15:24",
                           "userId":"74fe590d-9389-4936-abef-1c18fbf14750",
                            "client":{
                                    "id":"91dbc8c3-6df6-4702-9733-c84dd67bf1ed",
                                     "firstName":"Ryan",
                                     "middleName":"",
                                     "lastName":"Peterson",
                                     "dob":339989400000,
                                     "dedupClientId":"5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8"
                                  }
                            }
                     ],
                     "page":{
                        "size":1,
                        "totalElements":3,
                        "totalPages":3
                     }
                  }
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error: Token Not Valid
      description: Returns a list of the top eligible clients.
      operationId: GET_eligibleclients
      parameters:
        - name: spdattype
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
        - name: sort
          in: query
          required: false
          description: >
            To sort data while retrieving. Provide sorting field (if want to
            sort on multiple fields provide fields with comma separation) and
            order (asc,desc) with comma separation.
          schema:
            type: string
    post:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  added: true
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error: Token Not Valid
      description: >
        Will add client to the eligible list. Accept json having one or more
        clients.

        Allowed values for "spdatLabel" field are
        "FAMILY","YOUTH","SINGLE_ADULT"
      operationId: POST_eligibleclients
      requestBody:
        content:
          application/json:
            example:
              clientDedupId: 74520590-3eb3-11e7-85e4-06c37be0e663
              surveyType: Servey Type
              surveyScore: '17'
              programType: Program Type
              matched: true
              spdatLabel: SINGLE_ADULT
              zipcode: '53320'
              surveyDate: '05-05-2016 09:12'
              ignoreMatchProcess: true
              remarks: Client not interested
            schema:
              type: string
        required: true
  '/eligibleclients/{dedupClientId}':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                clientId: 800fa63b-8278-414c-83f1-5e29740205a0
                surveyScore: 10
                matched: false
                surveyDate: '09-03-2016 04:19'
                dateCreated: '10-25-2016 15:24'
                dateUpdated: '10-25-2016 15:24'
                userId: 74fe590d-9389-4936-abef-1c18fbf14750
                remarks: Clients eligible for housing unit
                ignoreMatchProcess: false
                client:
                  id: 800fa63b-8278-414c-83f1-5e29740205a0
                  firstName: Ryan
                  middleName: ''
                  lastName: Peterson
                  dob: 339989400000
                  dedupClientId: 5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8
                links:
                  - rel: client
                    href: /hmis-clientapi/rest/v2014/clients/800fa63b-8278-414c-83f1-5e29740205a0
              schema:
                $ref: "#/components/schemas/getdedupclient"
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error: Token Not Valid
        '404':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error: Resource Not Found
      description: Fetch a particular client
      operationId: GET_eligibleclients-dedupClientId
    delete:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  deleted: true
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error: Token Not Valid
        '404':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error: Resource Not Found
      description: Delete a particular client
      operationId: DELETE_eligibleclients-dedupClientId
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  updated: true
        '403':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error: Token Not Valid
      description: >
        An eligible client, who is already matched and assigned an housing unit
        can reject the referral (an assigned housig unit can be rejected for
        various reasons). When this happens, "ignoreMatchProcess" flag will be
        set to "true" and the hosuing unit will become vacant (available for
        matching process again) An eligible client, who rejected the refferal,
        can be made available for matching process by setting
        "ignoreMatchProcess" to FALSE.
      operationId: PUT_eligibleclients-dedupClientId
      requestBody:
        content:
          application/json:
            example:
              surveyType: Servey Type
              surveyScore: '10'
              programType: Program Type
              matched: false
              spdatLabel: SINGLE_ADULT
              zipcode: '53320'
              surveyDate: '05-05-2016 12:12'
              remarks: Client data updated
            schema:
              $ref: "#/components/schemas/putdedupclient"
        required: true
    parameters:
      - name: dedupClientId
        in: path
        required: true
        schema:
          type: string
        description: id of the client.
  '/matches/client/{dedupClientId}/status':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                example:
                  - id: ec501234-c61a-48bd-a85e-580af887a6a4
                    clientId: 6f38e63f-7856-4fb1-838f-c03805eab244
                    dedupClientId: 5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8
                    status: 3
                    statusDescription: Agency scheduled appointment with Client
                    recipients: {}
                    active: false
                    dateCreated: '10-25-2016 15:24'
                    dateUpdated: '10-25-2016 15:24'
                    userId: 74fe590d-9389-4936-abef-1c18fbf14750
                  - id: d406dbb7-cda3-4879-9e5d-989d5bc67b16
                    clientId: 6f38e63f-7856-4fb1-838f-c03805eab244
                    dedupClientId: 5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8
                    status: 2
                    statusDescription: Client is contacted by Agency
                    recipients: {}
                    active: false
                    dateCreated: '10-13-2016 02:26:09.066'
                    dateUpdated: '10-13-2016 02:26:09.066'
                    userId: 74fe590d-9389-4936-abef-1c18fbf14750
                  - id: d4c767bc-cb85-44f9-a985-0447292fedf6
                    clientId: 6f38e63f-7856-4fb1-838f-c03805eab244
                    dedupClientId: 5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8
                    status: 1
                    statusDescription: Email sent to Referral Agency
                    recipients: {}
                    active: false
                    dateCreated: '10-13-2016 02:23:59.124'
                    dateUpdated: '10-13-2016 02:23:59.124'
                    userId: 74fe590d-9389-4936-abef-1c18fbf14750
        '404':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error:
                    - code: ERR_CODE_CLIENT_NOT_FOUND
                      message: Client not found
      description: TO read a client status history
      operationId: GET_matches-client-dedupClientId-status
    put:
      responses:
        '200':
          description: ''
        '400':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error:
                    - code: ERR_CODE_INVALID_STATUS
                      message: Invalid status. Current status 1
        '404':
          description: ''
          content:
            application/json:
              schema:
                example:
                  error:
                    - code: ERR_CODE_CLIENT_NOT_FOUND
                      message: Client not found
      description: |
        Updates the status of a client matching. A notification will be
        triggered to the list of recipients set in the request body (recicipents
        can be part of TO,CC, BCC). Also the notification will be CC'ed to
        logged-in user (who is authorized to take actions for status to progress
        to the next levels). User can provide additional comments as well while
        updating the status of a specific match. Currently, the following are
        the statuses that are allowed

          Status 1 - Email sent to Referral Agency
          Status 2 - Client is contacted by Agency
          Status 3 - Agency scheduled appointment with Client
          Status 4 - Client missed 1st appointment
          Status 5 - Client missed 2nd appointment
          Status 6 - Paperwork initiated by Agency
          Status 7 - Client accepted referral
          Status 8 - Move-in Preparation initiated by Agency
          Status 9 - Client moved in
          Status 10 - Referral is rejected
      operationId: PUT_matches-client-dedupClientId-status
      requestBody:
        content:
          application/json:
            example:
              status: '1'
              comments: forwarding to next level
              recipients:
                toRecipients:
                  - agent@gmail.com
                  - client@hmis.com
                bccRecipients:
                  - agent@gmail.com
                  - client@hmis.com
                ccRecipients:
                  - agent@gmail.com
                  - client@hmis.com
            schema:
              $ref: "#/components/schemas/putstatusrequest"
        required: true
    parameters:
      - name: dedupClientId
        in: path
        required: true
        schema:
          type: string
components:
  schemas: 
    getdedupclient:
      properties:
        clientId:
          type: string
        dateCreated:
          type: string
        dateUpdated:
          type: string
        ignoreMatchProcess:
          type: boolean
        client:
          type: object
          properties:
            id:
              type: string
            firstName:
              type: string
            middleName:
              type: string
            lastName:
              type: string
            dob:
              type: number
        links:
          items:
            additionalProperties: false
            properties:
              href:
                type: string
              rel:
                type: string
            required:
              - href
              - rel
            type: object
          type: array
        matched:
          type: boolean
        remarks:
          type: string
        surveyDate:
          type: string
        surveyScore:
          type: integer
        userId:
          type: string
      type: object
      
    putdedupclient:
      properties:
        matched:
          type: boolean
        programType:
          type: string
        spdatLabel:
          type: string
        surveyDate:
          type: string
        surveyScore:
          type: string
        surveyType:
          type: string
        zipcode:
          type: string
        remarks:
          type: string
      required:
        - spdatLabel
        - surveyScore
        - matched
      type: object
  
    putstatusrequest:
      type: object
      properties:
        status:
          type: string
        comments:
          type: string
        recipients:
          type: object
      required:
        - status
        - comments
        - recipients
  
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    oauth_2_0:
      description: |
        The HMIS API supports OAuth 2.0 for authenticating all API requests.
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://hmislynk.com/hmis-authorization-service/rest/token'
          scopes:
            user: ''
            administrator: ''
  links: {}
  callbacks: {}